version: '3'

services:
  microservice:
    build:
      context: './microservice-template'
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./microservice-template/src:/home/node/app/src
      - ./microservice-template/nodemon.json:/home/node/app/nodemon.json
    expose:
      - '3000'
    ports:
      - "3001:3000"
    command: npm run dev
    depends_on: 
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/microservices
  db:
    image: mongo
    ports:
      - "27017:27017"

  nginx:
    image: nginx:latest
    ports:
      - "4000:4000"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - microservice