version: '3'

services:
  # Microservices
  microservice-auth:
    build:
      context: './microservice-auth'
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./microservice-auth/src:/home/node/app/src
      - ./microservice-auth/nodemon.json:/home/node/app/nodemon.json
    expose:
      - '3000'
    ports:
      - "3002:3000"
    command: npm run dev
    depends_on: 
      - mysql
    environment:
      - DATABASE_URL=mysql://root:root@mysql/cesi-eat
      - PORT=3000
  microservice-cdn:
    build:
      context: './microservice-cdn'
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./microservice-cdn/src:/home/node/app/src
      - ./microservice-cdn/nodemon.json:/home/node/app/nodemon.json
    expose:
      - '3000'
    ports:  
      - "3003:3000"
    command: npm run dev
    environment:
      - PORT=3000
  microservice-restaurants:
    build:
      context: './microservice-restaurants'
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./microservice-restaurants/src:/home/node/app/src
      - ./microservice-restaurants/nodemon.json:/home/node/app/nodemon.json
    expose:
      - '3000'
    ports:
      - "3004:3000"
    command: npm run dev
    depends_on: 
      - mongo
    environment:
      - DATABASE_URL=mongodb://mongo/cesi-eat-db
      - PORT=3000
  # Databases
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ~/apps/mongo:/data/db
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - "3307:3306"
    volumes:
      - ~/apps/mysql:/var/lib/mysql

  nginx:
    image: nginx:latest
    ports:
      - "4000:4000"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - microservice-auth
      - microservice-cdn
      - microservice-restaurants